metric: COCO
num_classes: 80


TrainDataset:
  !COCODataSet
    image_dir: train2017 # images
    anno_path: labels/instances_train2017.json
    dataset_dir: ./data/coco/train/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', "proposal_box"]
    pro_path: ./data/coco_2017_train_box_proposals.pkl
    pro_topk: 2000

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: labels/instances_val2017.json
    dataset_dir: ./data/coco/val/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', "proposal_box"]
    pro_path: ./data/coco/val/coco_2017_val_box_proposals.pkl
    pro_topk: 1000

TestDataset:
  !ImageFolder
    anno_path: ./data/coco/val/labels/instances_val2017.json
